name: build-images

"on":
  push:
    paths:
      - .github/workflows/build-images.yml

jobs:
  buildx:
    strategy:
      matrix:
        component:
          - sidecar
          - initupload
          - clonerefs
          - bootstrap

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
        with:
          driver-opts: network=host

      - uses: docker/login-action@v1
        name: Login ghcr.io
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - uses: docker/build-push-action@v2
        with:
          context: ./images/${{ matrix.component }}
          platforms: linux/amd64,linux/arm64
          labels: |
            org.opencontainers.image.source=https://github.com/${{ github.repository }}
            org.opencontainers.image.revision=${{ steps.prepare.outputs.tag }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ghcr.io/${{ github.repository }}/${{ matrix.component }}:latest
